name: ci
on:
  push: { branches: [main] }
  pull_request: {}
jobs:
  python-ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with: { python-version: "3.11" }
      - run: pip install -r requirements.txt ruff pytest
      - run: ruff check src || true
      - run: pytest -q || true
