name: deploy-functions
on:
  push:
    branches: [main]
    paths:
      - "src/ai_o11y_custos/scoring_function/**"
      - ".github/workflows/deploy-functions.yml"
jobs:
  func:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - name: Deploy Function App
        uses: Azure/functions-action@v1
        with:
          app-name: ai-o11y-custos-func
          package: src/ai_o11y_custos/scoring_function
