name: deploy-infra
on:
  push:
    paths: ["infra/**"]
    branches: [main]
jobs:
  tf:
    runs-on: ubuntu-latest
    permissions: { id-token: write, contents: read }
    steps:
      - uses: actions/checkout@v4
      - uses: azure/login@v2
        with: { creds: ${{ secrets.AZURE_CREDENTIALS }} }
      - uses: hashicorp/setup-terraform@v3
      - working-directory: infra
        run: |
          terraform init -input=false
          terraform validate
          terraform apply -auto-approve -input=false
